### ISSUE TITLE
When repo was moved custom-elements-es5-adapter.js was lost. We need it

### ISSUE THREAD

**Issue by cekvenich** [webcomponents/polyfills#209]
The old repo ( https://github.com/webcomponents/webcomponentsjs )
had this file: custom-elements-es5-adapter.js
( https://cdn.jsdelivr.net/npm/@webcomponents/webcomponentsjs@2.2.10/custom-elements-es5-adapter.js )
Since then it says repo was moved AND you also had a new release 2.3.

That file is needed as a polyfill for ES5 support of custom elements. 
Where is the new version of this file?

The documentation refers to it here (and also external tutorials).

**Comment by cekvenich** [comment]
Here is the readme  that talks about the file that was lost when repo was moved: 
https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs
That file no longer exists.

**Comment by alienriver49** [comment]
Since this is now a monorepo, everything from https://github.com/webcomponents/webcomponentsjs was moved under https://github.com/webcomponents/polyfills/blob/master/packages/webcomponentsjs Any of the packages that had individual repos on Github now live under the `packages` folder.

So for the ES5 Adapter, that's located at:
https://github.com/webcomponents/polyfills/blob/master/packages/webcomponentsjs/src/entrypoints/custom-elements-es5-adapter-index.js

Which then just imports this:
https://github.com/webcomponents/polyfills/blob/master/packages/custom-elements/src/native-shim.js

This is the same as what was in the previous repo. If you run `npm install @webcomponents/webcomponentsjs@^2.3.0` you'll find that ES5 adapter in the folder `node_modules/@webcomponents/webcomponentsjs`. That's how I've been getting the ES5 adapter.

**Comment by cekvenich** [comment]
thx
