### ISSUE TITLE
Disable scoping shim for one selector, or one stylesheet

### ISSUE THREAD

**Issue by rhyst** [webcomponents/polyfills#367]
Is there a way to disable scoping shim for a particular selector, or for an entire stylesheet? If I want a style to be unscoped/global?

I would expect perhaps :root to do this but it does not seem to:

```
:root .my-selector {

}
```

**Comment by aomarks** [comment]
The scoping shim only takes effect for styles within element templates that are passed to `prepareTemplate`, or to main-document styles passed to `CustomStyleInterface.addCustomStyle`. So, if you declare a style in your main document, and don't pass it to `addCustomStyle`, then ShadyCSS won't touch it.

But note this will _only_ work when the polyfill is enabled, since when native shadow DOM is operating, those styles won't apply to any shadow roots.
