### ISSUE TITLE
[WCJS] document.write does not work when webcomponents-loader.js is loaded asynchronously

### ISSUE THREAD

**Issue by pshihn** [webcomponents/polyfills#57]
If webcomponents-loader.js is loaded asynchronously and `document.readystate` is still 'loading' `document.write` in  [line 161](https://github.com/webcomponents/webcomponentsjs/blob/master/webcomponents-loader.js#L161 ) does not work. 

In Firefox, for example, it gives the following warning:
A call to document.write() from an asynchronously-loaded external script was ignored.

**Comment by azakus** [comment]
webcomponents-loader.js does handle being loaded async with v2

**Comment by bschlenk** [comment]
This doesn't seem to be fixed in v2, I'm seeing the same issue as reported in https://github.com/webcomponents/polyfills/issues/57. I've come to the same conclusion as https://github.com/webcomponents/polyfills/issues/57#issuecomment-429949554, that `document.readyState === 'loading'` does not guarantee that the script was loaded synchronously. It could also be that the `<head>` has lots of scripts in them and that the document still isn't ready.

I'm trying to understand why this was closed, it looks like the solution from https://github.com/webcomponents/webcomponentsjs/pull/1036 was never merged in. I have a "fix" working locally that involves replacing [this](https://github.com/webcomponents/polyfills/blob/ee5fb82a1a3560455726e63c5b4ca7e388d6f390/packages/webcomponentsjs/webcomponents-loader.js#L160) `document.write` with a `document.head.appendChild`. But I think this still runs into the issue that it doesn't guarantee that the polyfills are loaded before scripts that come after the asset loader.
