### ISSUE TITLE
[ShadyDOM] Missing `delegatesFocus` feature for attachShadow()

### ISSUE THREAD

**Issue by smalluban** [webcomponents/polyfills#87]
One of the users of [hybrids](https://github.com/hybridsjs/hybrids) library (UI library for creating web components) asked for support `deletagesFocus` feature of the Shadow DOM (https://github.com/hybridsjs/hybrids/issues/13). Surprisingly, I wasn't aware of that feature.

These are links to the specs and issue on GitHub (The issue is from 2015):
https://w3c.github.io/webcomponents/spec/shadow/#focus
https://github.com/w3c/webcomponents/issues/126

I searched for "delegatesFocus" in this repository, but with no luck to find anything. The code for `attachShadow` for now uses only `"mode"` option: https://github.com/webcomponents/shadydom/blob/e0e5db6cdd23aed5df30b49d73f309b179b7e4bd/src/attach-shadow.js#L58

I have started implementing a feature for the hybrids library and discovered, that it works in all native implementations - Chrome, Safari and Firefox (with turn on flags). However, for polyfilled browsers, obviously, it doesn't.

Are there any plans to support that feature? 

EDIT: Ok, my test was a little bit wrong about support... I checked a demo page linked from some discussion (https://takayoshikochi.github.io/tabindex-focus-navigation-explainer/demo/date-input.html) and now I am more confused about it. It uses `'delegatesFocus' in ShadowRoot.prototype` code to check support, so I checked it for Safari and Firefox. They don't support it... And that demo looks like it works with or without `delegatesFocus` switch actually the same...

**Comment by ianldgs** [comment]
This is quite important if you have a styleguide/component library with a button or input component that uses the shadow dom, given `delegatesFocus` is not supported on Safari and Firefox.

For anyone looking at this, you could use: https://github.com/calebdwilliams/delegates-focus-polyfill, but might need some fixes.

I ended up with a `shadow-focus-portal` component that also automatically adds `tabindex` to the parent element, so that it's          easily findable by `.querySelector('[tabindex]:not([tabindex="-1"]')`, but has some downsides.
